name: 'Files Changed Action'
description: 'An action to list out the files that have changed in this pull-request. Useful when combined with actions that want to run linters on a subset of files.'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  base:
    required: false
    description: 'The base ref to use (defaults to GITHUB_BASE_REF)'
outputs:
  files:
    description: 'A list of the files that have changed, separated by :::'
branding:
  icon: file
  color: green